version: '2'
services:
    jhhelloworld-app:
        image: jhhelloworld
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhhelloworld-postgresql:5432/jhHelloWorld
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhhelloworld-postgresql:
        extends:
            file: postgresql.yml
            service: jhhelloworld-postgresql
